<a href="https://colab.research.google.com/github/mdsahidraza174-netizen/api-data-preprocessing/blob/main/apifetching.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import requests

In [3]:
response = requests.get('https://api.the-odds-api.com/v4/sports/soccer_epl/odds/?apiKey=e09d222eb740724ac22129f7132ad111&regions=uk&markets=h2h')

In [4]:
response.json()

[{'id': '31c28f74ac0a0f65eeff8515ec593368',
  'sport_key': 'soccer_epl',
  'sport_title': 'EPL',
  'commence_time': '2026-05-09T11:30:00Z',
  'home_team': 'Liverpool',
  'away_team': 'Chelsea',
  'bookmakers': [{'key': 'betfred_uk',
    'title': 'Betfred (UK)',
    'last_update': '2026-05-08T04:35:24Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:24Z',
      'outcomes': [{'name': 'Chelsea', 'price': 3.6},
       {'name': 'Liverpool', 'price': 1.9},
       {'name': 'Draw', 'price': 4.2}]}]},
   {'key': 'unibet_uk',
    'title': 'Unibet (UK)',
    'last_update': '2026-05-08T04:35:25Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:25Z',
      'outcomes': [{'name': 'Chelsea', 'price': 3.75},
       {'name': 'Liverpool', 'price': 1.88},
       {'name': 'Draw', 'price': 4.0}]}]},
   {'key': 'skybet',
    'title': 'Sky Bet',
    'last_update': '2026-05-08T04:35:25Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:25Z',
      'outcomes': [{'name': 'Chelsea', 'price': 3.8},
       {'name': 'Liverpool', 'price': 1.8},
       {'name': 'Draw', 'price': 3.9}]}]},
   {'key': 'smarkets',
    'title': 'Smarkets',
    'last_update': '2026-05-08T04:35:14Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:14Z',
      'outcomes': [{'name': 'Chelsea', 'price': 4.1},
       {'name': 'Liverpool', 'price': 1.89},
       {'name': 'Draw', 'price': 4.1}]},
     {'key': 'h2h_lay',
      'last_update': '2026-05-08T04:35:14Z',
      'outcomes': [{'name': 'Chelsea', 'price': 4.3},
       {'name': 'Liverpool', 'price': 1.91},
       {'name': 'Draw', 'price': 4.2}]}]},
   {'key': 'paddypower',
    'title': 'Paddy Power',
    'last_update': '2026-05-08T04:36:03Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:36:03Z',
      'outcomes': [{'name': 'Chelsea', 'price': 3.8},
       {'name': 'Liverpool', 'price': 1.8},
       {'name': 'Draw', 'price': 3.8}]}]},
   {'key': 'boylesports',
    'title': 'BoyleSports',
    'last_update': '2026-05-08T04:34:02Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:34:02Z',
      'outcomes': [{'name': 'Chelsea', 'price': 3.8},
       {'name': 'Liverpool', 'price': 1.8},
       {'name': 'Draw', 'price': 3.8}]}]},
   {'key': 'betway',
    'title': 'Betway',
    'last_update': '2026-05-08T04:35:24Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:24Z',
      'outcomes': [{'name': 'Chelsea', 'price': 3.75},
       {'name': 'Liverpool', 'price': 1.83},
       {'name': 'Draw', 'price': 4.0}]}]},
   {'key': 'sport888',
    'title': '888sport',
    'last_update': '2026-05-08T04:35:11Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:11Z',
      'outcomes': [{'name': 'Chelsea', 'price': 3.7},
       {'name': 'Liverpool', 'price': 1.85},
       {'name': 'Draw', 'price': 3.8}]}]},
   {'key': 'williamhill',
    'title': 'William Hill',
    'last_update': '2026-05-08T04:35:11Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:11Z',
      'outcomes': [{'name': 'Chelsea', 'price': 3.7},
       {'name': 'Liverpool', 'price': 1.85},
       {'name': 'Draw', 'price': 3.8}]}]},
   {'key': 'betfair_ex_uk',
    'title': 'Betfair',
    'last_update': '2026-05-08T04:35:42Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:42Z',
      'outcomes': [{'name': 'Chelsea', 'price': 4.1},
       {'name': 'Liverpool', 'price': 1.9},
       {'name': 'Draw', 'price': 4.1}]},
     {'key': 'h2h_lay',
      'last_update': '2026-05-08T04:35:42Z',
      'outcomes': [{'name': 'Chelsea', 'price': 4.3},
       {'name': 'Liverpool', 'price': 1.91},
       {'name': 'Draw', 'price': 4.2}]}]},
   {'key': 'leovegas',
    'title': 'LeoVegas',
    'last_update': '2026-05-08T04:35:11Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:11Z',
      'outcomes': [{'name': 'Chelsea', 'price': 3.9},
       {'name': 'Liverpool', 'price': 1.77},
       {'name': 'Draw', 'price': 4.1}]}]},
   {'key': 'livescorebet',
    'title': 'LiveScore Bet',
    'last_update': '2026-05-08T04:35:10Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:10Z',
      'outcomes': [{'name': 'Chelsea', 'price': 3.7},
       {'name': 'Liverpool', 'price': 1.71},
       {'name': 'Draw', 'price': 3.95}]}]},
   {'key': 'casumo',
    'title': 'Casumo',
    'last_update': '2026-05-08T04:36:04Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:36:04Z',
      'outcomes': [{'name': 'Chelsea', 'price': 3.95},
       {'name': 'Liverpool', 'price': 1.79},
       {'name': 'Draw', 'price': 4.2}]}]},
   {'key': 'virginbet',
    'title': 'Virgin Bet',
    'last_update': '2026-05-08T04:35:11Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:10Z',
      'outcomes': [{'name': 'Chelsea', 'price': 3.7},
       {'name': 'Liverpool', 'price': 1.71},
       {'name': 'Draw', 'price': 3.95}]}]},
   {'key': 'grosvenor',
    'title': 'Grosvenor',
    'last_update': '2026-05-08T04:35:11Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:11Z',
      'outcomes': [{'name': 'Chelsea', 'price': 3.95},
       {'name': 'Liverpool', 'price': 1.79},
       {'name': 'Draw', 'price': 4.2}]}]},
   {'key': 'betvictor',
    'title': 'Bet Victor',
    'last_update': '2026-05-08T04:34:28Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:34:28Z',
      'outcomes': [{'name': 'Chelsea', 'price': 4.0},
       {'name': 'Liverpool', 'price': 1.8},
       {'name': 'Draw', 'price': 4.0}]}]},
   {'key': 'matchbook',
    'title': 'Matchbook',
    'last_update': '2026-05-08T04:35:44Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:43Z',
      'outcomes': [{'name': 'Chelsea', 'price': 4.1},
       {'name': 'Liverpool', 'price': 1.91},
       {'name': 'Draw', 'price': 4.1}]},
     {'key': 'h2h_lay',
      'last_update': '2026-05-08T04:35:43Z',
      'outcomes': [{'name': 'Chelsea', 'price': 4.2},
       {'name': 'Liverpool', 'price': 1.92},
       {'name': 'Draw', 'price': 4.2}]}]},
   {'key': 'betfair_sb_uk',
    'title': 'Betfair Sportsbook',
    'last_update': '2026-05-08T04:35:10Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:10Z',
      'outcomes': [{'name': 'Chelsea', 'price': 3.5},
       {'name': 'Liverpool', 'price': 1.73},
       {'name': 'Draw', 'price': 3.5}]}]},
   {'key': 'ladbrokes_uk',
    'title': 'Ladbrokes',
    'last_update': '2026-05-08T04:34:55Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:34:55Z',
      'outcomes': [{'name': 'Chelsea', 'price': 3.8},
       {'name': 'Liverpool', 'price': 1.83},
       {'name': 'Draw', 'price': 4.0}]}]},
   {'key': 'coral',
    'title': 'Coral',
    'last_update': '2026-05-08T04:33:46Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:33:46Z',
      'outcomes': [{'name': 'Chelsea', 'price': 3.8},
       {'name': 'Liverpool', 'price': 1.83},
       {'name': 'Draw', 'price': 4.0}]}]}]},
 {'id': '0568f4e3240e33cd97331e3e6b5ae536',
  'sport_key': 'soccer_epl',
  'sport_title': 'EPL',
  'commence_time': '2026-05-09T14:00:00Z',
  'home_team': 'Fulham',
  'away_team': 'Bournemouth',
  'bookmakers': [{'key': 'unibet_uk',
    'title': 'Unibet (UK)',
    'last_update': '2026-05-08T04:35:25Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:25Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.45},
       {'name': 'Fulham', 'price': 2.75},
       {'name': 'Draw', 'price': 3.6}]}]},
   {'key': 'boylesports',
    'title': 'BoyleSports',
    'last_update': '2026-05-08T04:34:02Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:34:02Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.38},
       {'name': 'Fulham', 'price': 2.62},
       {'name': 'Draw', 'price': 3.6}]}]},
   {'key': 'betway',
    'title': 'Betway',
    'last_update': '2026-05-08T04:35:24Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:24Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.38},
       {'name': 'Fulham', 'price': 2.75},
       {'name': 'Draw', 'price': 3.6}]}]},
   {'key': 'betfred_uk',
    'title': 'Betfred (UK)',
    'last_update': '2026-05-08T04:35:24Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:24Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.38},
       {'name': 'Fulham', 'price': 2.75},
       {'name': 'Draw', 'price': 3.75}]}]},
   {'key': 'sport888',
    'title': '888sport',
    'last_update': '2026-05-08T04:35:11Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:11Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.38},
       {'name': 'Fulham', 'price': 2.7},
       {'name': 'Draw', 'price': 3.5}]}]},
   {'key': 'williamhill',
    'title': 'William Hill',
    'last_update': '2026-05-08T04:35:11Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:11Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.38},
       {'name': 'Fulham', 'price': 2.7},
       {'name': 'Draw', 'price': 3.5}]}]},
   {'key': 'skybet',
    'title': 'Sky Bet',
    'last_update': '2026-05-08T04:35:25Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:25Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.38},
       {'name': 'Fulham', 'price': 2.7},
       {'name': 'Draw', 'price': 3.6}]}]},
   {'key': 'paddypower',
    'title': 'Paddy Power',
    'last_update': '2026-05-08T04:36:03Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:36:03Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.38},
       {'name': 'Fulham', 'price': 2.7},
       {'name': 'Draw', 'price': 3.6}]}]},
   {'key': 'smarkets',
    'title': 'Smarkets',
    'last_update': '2026-05-08T04:35:14Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:14Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.44},
       {'name': 'Fulham', 'price': 2.88},
       {'name': 'Draw', 'price': 3.85}]},
     {'key': 'h2h_lay',
      'last_update': '2026-05-08T04:35:14Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.5},
       {'name': 'Fulham', 'price': 2.94},
       {'name': 'Draw', 'price': 4.0}]}]},
   {'key': 'betfair_ex_uk',
    'title': 'Betfair',
    'last_update': '2026-05-08T04:35:42Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:42Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.46},
       {'name': 'Fulham', 'price': 2.9},
       {'name': 'Draw', 'price': 3.9}]},
     {'key': 'h2h_lay',
      'last_update': '2026-05-08T04:35:42Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.5},
       {'name': 'Fulham', 'price': 2.94},
       {'name': 'Draw', 'price': 4.0}]}]},
   {'key': 'casumo',
    'title': 'Casumo',
    'last_update': '2026-05-08T04:36:04Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:36:04Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.45},
       {'name': 'Fulham', 'price': 2.7},
       {'name': 'Draw', 'price': 3.7}]}]},
   {'key': 'virginbet',
    'title': 'Virgin Bet',
    'last_update': '2026-05-08T04:35:11Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:10Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.3},
       {'name': 'Fulham', 'price': 2.6},
       {'name': 'Draw', 'price': 3.45}]}]},
   {'key': 'grosvenor',
    'title': 'Grosvenor',
    'last_update': '2026-05-08T04:35:11Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:11Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.45},
       {'name': 'Fulham', 'price': 2.7},
       {'name': 'Draw', 'price': 3.7}]}]},
   {'key': 'leovegas',
    'title': 'LeoVegas',
    'last_update': '2026-05-08T04:35:11Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:11Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.43},
       {'name': 'Fulham', 'price': 2.65},
       {'name': 'Draw', 'price': 3.65}]}]},
   {'key': 'livescorebet',
    'title': 'LiveScore Bet',
    'last_update': '2026-05-08T04:35:10Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:10Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.3},
       {'name': 'Fulham', 'price': 2.6},
       {'name': 'Draw', 'price': 3.45}]}]},
   {'key': 'betvictor',
    'title': 'Bet Victor',
    'last_update': '2026-05-08T04:34:28Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:34:28Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.3},
       {'name': 'Fulham', 'price': 2.7},
       {'name': 'Draw', 'price': 3.75}]}]},
   {'key': 'betfair_sb_uk',
    'title': 'Betfair Sportsbook',
    'last_update': '2026-05-08T04:35:10Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:10Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.25},
       {'name': 'Fulham', 'price': 2.6},
       {'name': 'Draw', 'price': 3.2}]}]},
   {'key': 'matchbook',
    'title': 'Matchbook',
    'last_update': '2026-05-08T04:35:44Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:43Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.46},
       {'name': 'Fulham', 'price': 2.9},
       {'name': 'Draw', 'price': 3.9}]},
     {'key': 'h2h_lay',
      'last_update': '2026-05-08T04:35:43Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.5},
       {'name': 'Fulham', 'price': 2.94},
       {'name': 'Draw', 'price': 4.0}]}]},
   {'key': 'ladbrokes_uk',
    'title': 'Ladbrokes',
    'last_update': '2026-05-08T04:34:55Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:34:55Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.45},
       {'name': 'Fulham', 'price': 2.62},
       {'name': 'Draw', 'price': 3.6}]}]},
   {'key': 'coral',
    'title': 'Coral',
    'last_update': '2026-05-08T04:33:46Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:33:46Z',
      'outcomes': [{'name': 'Bournemouth', 'price': 2.45},
       {'name': 'Fulham', 'price': 2.62},
       {'name': 'Draw', 'price': 3.7}]}]}]},
 {'id': 'a68b8df178cb76213ef7eb8a83b0762c',
  'sport_key': 'soccer_epl',
  'sport_title': 'EPL',
  'commence_time': '2026-05-09T14:00:00Z',
  'home_team': 'Brighton and Hove Albion',
  'away_team': 'Wolverhampton Wanderers',
  'bookmakers': [{'key': 'unibet_uk',
    'title': 'Unibet (UK)',
    'last_update': '2026-05-08T04:35:25Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:25Z',
      'outcomes': [{'name': 'Brighton and Hove Albion', 'price': 1.27},
       {'name': 'Wolverhampton Wanderers', 'price': 10.0},
       {'name': 'Draw', 'price': 6.0}]}]},
   {'key': 'betway',
    'title': 'Betway',
    'last_update': '2026-05-08T04:35:24Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:24Z',
      'outcomes': [{'name': 'Brighton and Hove Albion', 'price': 1.29},
       {'name': 'Wolverhampton Wanderers', 'price': 9.0},
       {'name': 'Draw', 'price': 6.0}]}]},
   {'key': 'betfred_uk',
    'title': 'Betfred (UK)',
    'last_update': '2026-05-08T04:35:24Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:24Z',
      'outcomes': [{'name': 'Brighton and Hove Albion', 'price': 1.29},
       {'name': 'Wolverhampton Wanderers', 'price': 11.0},
       {'name': 'Draw', 'price': 5.5}]}]},
   {'key': 'paddypower',
    'title': 'Paddy Power',
    'last_update': '2026-05-08T04:36:03Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:36:03Z',
      'outcomes': [{'name': 'Brighton and Hove Albion', 'price': 1.22},
       {'name': 'Wolverhampton Wanderers', 'price': 10.0},
       {'name': 'Draw', 'price': 6.0}]}]},
   {'key': 'skybet',
    'title': 'Sky Bet',
    'last_update': '2026-05-08T04:35:25Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:25Z',
      'outcomes': [{'name': 'Brighton and Hove Albion', 'price': 1.25},
       {'name': 'Wolverhampton Wanderers', 'price': 10.0},
       {'name': 'Draw', 'price': 6.0}]}]},
   {'key': 'boylesports',
    'title': 'BoyleSports',
    'last_update': '2026-05-08T04:34:02Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:34:02Z',
      'outcomes': [{'name': 'Brighton and Hove Albion', 'price': 1.25},
       {'name': 'Wolverhampton Wanderers', 'price': 10.0},
       {'name': 'Draw', 'price': 5.5}]}]},
   {'key': 'sport888',
    'title': '888sport',
    'last_update': '2026-05-08T04:35:11Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:11Z',
      'outcomes': [{'name': 'Brighton and Hove Albion', 'price': 1.25},
       {'name': 'Wolverhampton Wanderers', 'price': 9.5},
       {'name': 'Draw', 'price': 5.5}]}]},
   {'key': 'williamhill',
    'title': 'William Hill',
    'last_update': '2026-05-08T04:35:11Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:11Z',
      'outcomes': [{'name': 'Brighton and Hove Albion', 'price': 1.25},
       {'name': 'Wolverhampton Wanderers', 'price': 9.5},
       {'name': 'Draw', 'price': 5.5}]}]},
   {'key': 'smarkets',
    'title': 'Smarkets',
    'last_update': '2026-05-08T04:35:14Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:14Z',
      'outcomes': [{'name': 'Brighton and Hove Albion', 'price': 1.29},
       {'name': 'Wolverhampton Wanderers', 'price': 12.0},
       {'name': 'Draw', 'price': 6.6}]},
     {'key': 'h2h_lay',
      'last_update': '2026-05-08T04:35:14Z',
      'outcomes': [{'name': 'Brighton and Hove Albion', 'price': 1.3},
       {'name': 'Wolverhampton Wanderers', 'price': 13.0},
       {'name': 'Draw', 'price': 7.0}]}]},
   {'key': 'betfair_ex_uk',
    'title': 'Betfair',
    'last_update': '2026-05-08T04:35:42Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:42Z',
      'outcomes': [{'name': 'Brighton and Hove Albion', 'price': 1.29},
       {'name': 'Wolverhampton Wanderers', 'price': 12.0},
       {'name': 'Draw', 'price': 6.8}]},
     {'key': 'h2h_lay',
      'last_update': '2026-05-08T04:35:42Z',
      'outcomes': [{'name': 'Brighton and Hove Albion', 'price': 1.3},
       {'name': 'Wolverhampton Wanderers', 'price': 13.0},
       {'name': 'Draw', 'price': 7.0}]}]},
   {'key': 'grosvenor',
    'title': 'Grosvenor',
    'last_update': '2026-05-08T04:35:11Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:11Z',
      'outcomes': [{'name': 'Brighton and Hove Albion', 'price': 1.28},
       {'name': 'Wolverhampton Wanderers', 'price': 10.0},
       {'name': 'Draw', 'price': 6.0}]}]},
   {'key': 'leovegas',
    'title': 'LeoVegas',
    'last_update': '2026-05-08T04:35:11Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:11Z',
      'outcomes': [{'name': 'Brighton and Hove Albion', 'price': 1.26},
       {'name': 'Wolverhampton Wanderers', 'price': 10.0},
       {'name': 'Draw', 'price': 5.8}]}]},
   {'key': 'livescorebet',
    'title': 'LiveScore Bet',
    'last_update': '2026-05-08T04:35:10Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:10Z',
      'outcomes': [{'name': 'Brighton and Hove Albion', 'price': 1.23},
       {'name': 'Wolverhampton Wanderers', 'price': 8.5},
       {'name': 'Draw', 'price': 5.75}]}]},
   {'key': 'casumo',
    'title': 'Casumo',
    'last_update': '2026-05-08T04:36:04Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:36:04Z',
      'outcomes': [{'name': 'Brighton and Hove Albion', 'price': 1.28},
       {'name': 'Wolverhampton Wanderers', 'price': 10.0},
       {'name': 'Draw', 'price': 6.0}]}]},
   {'key': 'virginbet',
    'title': 'Virgin Bet',
    'last_update': '2026-05-08T04:35:11Z',
    'markets': [{'key': 'h2h',
      'last_update': '2026-05-08T04:35:10Z',
      'outcomes': [{'name': 'Brighton and Hove Albion', 'price': 1.23},
       {'name': 'Wolverhampton Wanderers', 'price': 8.5},

In [5]:
pd.DataFrame(response.json())

,id,sport_key,sport_title,commence_time,home_team,away_team,bookmakers
0,31c28f74ac0a0f65eeff8515ec593368,soccer_epl,EPL,2026-05-09T11:30:00Z,Liverpool,Chelsea,"[{'key': 'betfred_uk', 'title': 'Betfred (UK)'..."
1,0568f4e3240e33cd97331e3e6b5ae536,soccer_epl,EPL,2026-05-09T14:00:00Z,Fulham,Bournemouth,"[{'key': 'unibet_uk', 'title': 'Unibet (UK)', ..."
2,a68b8df178cb76213ef7eb8a83b0762c,soccer_epl,EPL,2026-05-09T14:00:00Z,Brighton and Hove Albion,Wolverhampton Wanderers,"[{'key': 'unibet_uk', 'title': 'Unibet (UK)', ..."
3,edb41dc3458757ffd26876af02c729fb,soccer_epl,EPL,2026-05-09T14:00:00Z,Sunderland,Manchester United,"[{'key': 'betway', 'title': 'Betway', 'last_up..."
4,c1c798a177c51362dce45113112e0d3d,soccer_epl,EPL,2026-05-09T16:30:00Z,Manchester City,Brentford,"[{'key': 'smarkets', 'title': 'Smarkets', 'las..."
5,d886f96ec9255bad51c2b93ebf5067f2,soccer_epl,EPL,2026-05-10T13:00:00Z,Burnley,Aston Villa,"[{'key': 'betfred_uk', 'title': 'Betfred (UK)'..."
6,05192f677ae85b891f6a652b5cbe8917,soccer_epl,EPL,2026-05-10T13:00:00Z,Crystal Palace,Everton,"[{'key': 'smarkets', 'title': 'Smarkets', 'las..."
7,b83b66eb2cc703413276e418724fd51f,soccer_epl,EPL,2026-05-10T13:00:00Z,Nottingham Forest,Newcastle United,"[{'key': 'betway', 'title': 'Betway', 'last_up..."
8,d75b633386ce973fb123df8b86120374,soccer_epl,EPL,2026-05-10T15:30:00Z,West Ham United,Arsenal,"[{'key': 'betway', 'title': 'Betway', 'last_up..."
9,6d8db9dded1c8d337ae3a570c8d4ff3c,soccer_epl,EPL,2026-05-11T19:00:00Z,Tottenham Hotspur,Leeds United,"[{'key': 'betway', 'title': 'Betway', 'last_up..."
10,25f172034a65aca643fc22203f5e4cb2,soccer_epl,EPL,2026-05-13T19:00:00Z,Manchester City,Crystal Palace,"[{'key': 'unibet_uk', 'title': 'Unibet (UK)', ..."
11,1c5214151ed7571cdad54fd8cdad6113,soccer_epl,EPL,2026-05-15T19:00:00Z,Aston Villa,Liverpool,"[{'key': 'leovegas', 'title': 'LeoVegas', 'las..."
12,80a2916e99de4f7181604ed375e3a99d,soccer_epl,EPL,2026-05-17T11:30:00Z,Aston Villa,Liverpool,"[{'key': 'unibet_uk', 'title': 'Unibet (UK)', ..."
13,7142bb335268525fa5116c2f62763fa0,soccer_epl,EPL,2026-05-17T11:30:00Z,Manchester United,Nottingham Forest,"[{'key': 'unibet_uk', 'title': 'Unibet (UK)', ..."
14,616cd9236437862ceceb47b6aec4a004,soccer_epl,EPL,2026-05-17T14:00:00Z,Brentford,Crystal Palace,"[{'key': 'unibet_uk', 'title': 'Unibet (UK)', ..."
15,80dfd4c3675149dca21da2943420629a,soccer_epl,EPL,2026-05-17T14:00:00Z,Leeds United,Brighton and Hove Albion,"[{'key': 'unibet_uk', 'title': 'Unibet (UK)', ..."
16,bd38142035040006cfb0ca9d6e3ab2be,soccer_epl,EPL,2026-05-17T14:00:00Z,Everton,Sunderland,"[{'key': 'betfred_uk', 'title': 'Betfred (UK)'..."
17,e0c6894a7376e3bacabd8e4c522a733e,soccer_epl,EPL,2026-05-17T14:00:00Z,Wolverhampton Wanderers,Fulham,"[{'key': 'unibet_uk', 'title': 'Unibet (UK)', ..."
18,f331171c7e14ee86e88f338343aa7f97,soccer_epl,EPL,2026-05-17T16:30:00Z,Newcastle United,West Ham United,"[{'key': 'betfred_uk', 'title': 'Betfred (UK)'..."
19,818582ac502774aad4bb82309b9b85fa,soccer_epl,EPL,2026-05-18T19:00:00Z,Arsenal,Burnley,"[{'key': 'betfred_uk', 'title': 'Betfred (UK)'..."

In [6]:
df = pd.DataFrame()

In [7]:
df

Empty DataFrame
Columns: []
Index: []

In [8]:
df = pd.DataFrame(response.json())

In [14]:
data = response.json()

In [15]:
rows = []

for match in data:
    for bookmaker in match['bookmakers']:
        rows.append({
            "home_team": match['home_team'],
            "away_team": match['away_team'],
            "bookmaker": bookmaker['title'],
            "last_update": bookmaker['last_update']
        })

In [16]:
df = pd.DataFrame(rows)

In [17]:
df

     home_team away_team     bookmaker           last_update
0    Liverpool   Chelsea  Betfred (UK)  2026-05-08T04:35:24Z
1    Liverpool   Chelsea   Unibet (UK)  2026-05-08T04:35:25Z
2    Liverpool   Chelsea       Sky Bet  2026-05-08T04:35:25Z
3    Liverpool   Chelsea      Smarkets  2026-05-08T04:35:14Z
4    Liverpool   Chelsea   Paddy Power  2026-05-08T04:36:03Z
..         ...       ...           ...                   ...
334    Arsenal   Burnley     Grosvenor  2026-05-08T04:35:11Z
335    Arsenal   Burnley        Casumo  2026-05-08T04:36:04Z
336    Arsenal   Burnley      888sport  2026-05-08T04:35:11Z
337    Arsenal   Burnley  William Hill  2026-05-08T04:35:11Z
338    Arsenal   Burnley   BoyleSports  2026-05-08T04:34:02Z

[339 rows x 4 columns]

In [18]:
df.to_csv("football_dataset.csv", index=False)